#!/bin/sh
#
# Public domain
# Author: roman [] tsisyk.com
#
# Modified by: dysoco [dsocolobsky@gmail.com]
#
# Usage: ./me url [youtube-dl parameters] [cache]
#

COOKIE_FILE=/var/tmp/youtube-dl-cookies.txt
mplayer -novideo -cache $2 -cookies -cookies-file ${COOKIE_FILE} $(youtube-dl -g --cookies ${COOKIE_FILE} $*)
